version: 2

models:
  - name: dim_crashes__conditions
    columns:
      - name: conditions_id
        description: The surrogate key of the conditions
        tests:
          - not_null
          - unique
  - name: dim_crashes__vehicles
    columns:
      - name: vehicle_id 
        description: The surrogate key of the vehicles.
        tests:
          - not_null
          - unique
  - name: dim_crashes__results
    columns:
      - name: result_id 
        description: The surrogate key of the results.
        tests:
          - not_null
          - unique
  - name: dim_crashes__reports
    columns:
      - name: report_id 
        description: The surrogate key of the reports.
        tests:
          - not_null
          - unique
  - name: fact_crashes
    columns:
      - name: report_id 
        description: The primary key of the crashes.
        tests:
          - not_null
          - unique